import type { Frames, SlotFrameProps } from "@malleable/react";
import { AnimatePresence, LayoutGroup, motion } from "motion/react";
import { createContext, useContext, type ReactNode } from "react";
import { easeOut, enter, exit } from "./kit";

export const ShowDecisions = createContext(false);

const BARE = new Set(["deadline-banner", "stat-strip"]);

const SOURCE_LABEL = { decider: " Jev", spec: " spec", default: " default" } as const;

function SlotFrame({ ref, def, order, fresh, keys, source, confidence, children }: SlotFrameProps) {
  const showDecisions = useContext(ShowDecisions);
  const bare = BARE.has(def.id);
  return (
    // Slots glide to their new place but take their new size at once: scaling a
    // slot to animate its size would stretch its text. New slots cascade in.
    <motion.section
      ref={ref}
      layout="position"
      layoutId={def.id}
      className="vbg-custom-slot"
      data-fresh={fresh || undefined}
      data-bare={bare || undefined}
      aria-label={def.title}
      initial={{ opacity: 0, y: 8 }}
      // Wait for the outgoing slot's fade to mostly clear before arriving, so two views never overlap.
      animate={{ opacity: 1, y: 0, transition: { ...enter, delay: 0.08 + Math.min(order, 4) * 0.04 } }}
      exit={{ opacity: 0, transition: exit }}
    >
      {(!bare || showDecisions) && (
        <header className="vbg-custom-slot-head">
          {!bare && <h2 className="vbg-heading-20">{def.title}</h2>}
          {showDecisions && (
            <p className="vbg-custom-variant">
              {Object.entries(def.props).map(([key, prop]) => (
                <span key={key} data-source={source[key]}>
                  <span className="vbg-custom-variant-key">{prop.label}</span>{" "}
                  <motion.span key={keys[key]} initial={{ opacity: 0.2 }} animate={{ opacity: 1 }} transition={{ duration: 0.4, ease: easeOut }}>
                    {keys[key]}
                  </motion.span>
                  <span className="vbg-custom-variant-src">
                    {SOURCE_LABEL[source[key] ?? "default"]}
                    {source[key] === "decider" && confidence[key] !== undefined && ` ${Math.round(confidence[key] * 100)}%`}
                  </span>
                </span>
              ))}
              {def.source === "generated" && <span data-source="generated">Generated by Claude</span>}
              {def.scope === "private" && <span data-source="generated">Only you</span>}
            </p>
          )}
        </header>
      )}
      {children}
    </motion.section>
  );
}

export const frames: Frames = {
  // Only the slots animate. The view and areas are invisible boxes, and
  // animating their size would scale, and so distort, everything inside them.
  view: ({ children }: { children: ReactNode }) => <LayoutGroup id="spec">{children}</LayoutGroup>,
  // Slots cascade in when a person's first view arrives, then only the pieces that change animate.
  area: ({ children }: { children: ReactNode }) => <AnimatePresence mode="popLayout">{children}</AnimatePresence>,
  slot: SlotFrame,
};
