import { AnimatePresence, LayoutGroup, motion } from "motion/react";
import { Suspense, useEffect, useRef, type ReactNode } from "react";
import { resolveProps, type ComponentDef, type Decision, type Layout, type Slot, type Spec } from "../../../shared/spec";
import { watchContrast } from "./contrast";
import { componentFor, SlotBoundary } from "./registry";

const spring = { type: "spring", stiffness: 260, damping: 32, mass: 0.9 } as const;

type Props = {
  spec: Spec;
  library: Record<string, ComponentDef>;
  viewId: string;
  decision: Decision | null;
  showDecisions: boolean;
  /** Slots that are new since the previous spec version, marked briefly. */
  fresh: Set<string>;
};

export function Renderer({ spec, library, viewId, decision, showDecisions, fresh }: Props) {
  const view = spec.views.find((v) => v.id === viewId) ?? spec.views.find((v) => v.id === spec.home) ?? spec.views[0];
  const current = decision && decision.view === view.id ? decision : null;
  const layout: Layout = current?.layout ?? view.layout;
  const regions = (["top", "main", "aside"] as const).map((r) => [r, view.slots.filter((s) => s.region === r)] as const);

  return (
    <LayoutGroup id="spec">
      <motion.div layout className="vbg-custom-view" data-layout={layout} transition={spring}>
        {regions.map(([region, slots]) =>
          slots.length === 0 ? null : (
            <motion.div layout key={region} className="vbg-custom-region" data-region={region} transition={spring}>
              <AnimatePresence mode="popLayout" initial={false}>
                {slots.map((slot) => (
                  <SlotFrame
                    key={slot.component}
                    slot={slot}
                    def={library[slot.component]}
                    chosen={current?.props[slot.id] ?? {}}
                    confidence={current?.propConfidence[slot.id] ?? {}}
                    showDecisions={showDecisions}
                    fresh={fresh.has(`${view.id}/${slot.id}`)}
                  />
                ))}
              </AnimatePresence>
            </motion.div>
          ),
        )}
      </motion.div>
    </LayoutGroup>
  );
}

function SlotFrame(p: {
  slot: Slot;
  def: ComponentDef | undefined;
  chosen: Record<string, string>;
  confidence: Record<string, number>;
  showDecisions: boolean;
  fresh: boolean;
}) {
  const { slot, def } = p;
  if (!def) return <p data-state="error">Unknown component {slot.component}</p>;
  const Component = componentFor(def);
  const props = resolveProps(def, slot, p.chosen);
  const bare = def.id === "deadline-banner" || def.id === "stat-strip";

  return (
    <motion.section
      layout
      layoutId={def.id}
      className="vbg-custom-slot"
      data-fresh={p.fresh || undefined}
      data-bare={bare || undefined}
      aria-label={def.title}
      initial={{ opacity: 0, y: 12, scale: 0.985 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, scale: 0.985, transition: { duration: 0.15 } }}
      transition={spring}
    >
      {(!bare || p.showDecisions) && (
        <motion.header layout="position" className="vbg-custom-slot-head">
          {!bare && <h2 className="vbg-heading-20">{def.title}</h2>}
          {p.showDecisions && (
            <p className="vbg-custom-variant">
              {Object.entries(def.props).map(([key, prop]) => {
                const adaptive = slot.adaptive.includes(key);
                const fixed = key in slot.props;
                return (
                  <span key={key} data-source={adaptive ? "jev" : fixed ? "spec" : "default"}>
                    <span className="vbg-custom-variant-key">{prop.label}</span>{" "}
                    <motion.span key={props[key]} initial={{ opacity: 0.2 }} animate={{ opacity: 1 }} transition={{ duration: 0.5 }}>
                      {props[key]}
                    </motion.span>
                    <span className="vbg-custom-variant-src">
                      {adaptive
                        ? p.confidence[key] !== undefined
                          ? ` Jev ${Math.round(p.confidence[key] * 100)}%`
                          : " Jev"
                        : fixed
                          ? " spec"
                          : " default"}
                    </span>
                  </span>
                );
              })}
              {def.source === "generated" && <span data-source="generated">Generated by Claude</span>}
            </p>
          )}
        </motion.header>
      )}
      <SlotBoundary name={def.title}>
        <Suspense fallback={<p className="vbg-meta">Loading {def.title}…</p>}>
          {!Component ? (
            <p data-state="error">No implementation for {def.id}</p>
          ) : def.source === "generated" ? (
            <ContrastGuard name={def.id}>
              <Component props={props} />
            </ContrastGuard>
          ) : (
            <Component props={props} />
          )}
        </Suspense>
      </SlotBoundary>
    </motion.section>
  );
}

/** Generated code passed the install audit, but data, themes and states change at runtime. */
function ContrastGuard({ name, children }: { name: string; children: ReactNode }) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => watchContrast(ref.current!, name), [name]);
  return (
    <div ref={ref} className="vbg-custom-guard">
      {children}
    </div>
  );
}
